### ISSUE TITLE
大佬能提供一下思路么。我想自己使用其他语言编译mac版本

### ISSUE THREAD

**Issue by HyHbh-dev** [cngege/GitHubDesktop2Chinese#1]
大佬能提供一下思路么。我想自己使用其他语言编译mac版本

**Comment by cngege** [comment]
最终原理就是替换main.js  和 render.js中的相关字符串
提前把要要替换的字符串写成[json列表](https://github.com/cngege/GitHubDesktop2Chinese/blob/master/json/localization.json)，然后写个程序自动定位最新版的两个js文件，读取GitHub上的json文件，遍历其中要替换的项，一个一个的替换

**Comment by cngege** [comment]
> 大佬能提供一下思路么。我想自己使用其他语言编译mac版本

最终原理就是替换main.js 和 render.js中的相关字符串
提前把要要替换的字符串写成[json列表](https://github.com/cngege/GitHubDesktop2Chinese/blob/master/json/localization.json)，然后写个程序自动定位最新版的两个js文件，读取GitHub上的json文件，遍历其中要替换的项，一个一个的替换

**Comment by 60999** [comment]
我用golang整了个版本，没有测试，带有自动升级，不知道要不要放出来。。提交到本项目合适么

**Comment by cngege** [comment]
> 我用golang整了个版本，没有测试，带有自动升级，不知道要不要放出来。。提交到本项目合适么

两个不同的项目放到一块不太合适，你自己的项目如果维护的话，我可以在readme添加个跳转链接，让用户可自由选择
