### ISSUE TITLE
Bug 反馈：汉化功能不稳定

### ISSUE THREAD

**Issue by afterow** [cngege/GitHubDesktop2Chinese#3]
## Bug Report

**描述**  
在汉化 GitHub Desktop 的过程中，重启后有概率汉化失效。

---

**环境**  
- **操作系统**: Windows 11  
- **GitHub Desktop 版本**: 3.4.12 (x64)  
- **汉化工具**: GitHubDesktop2Chinese v1.0.7  

---

**重现步骤**  
1. 打开 GitHub Desktop 应用程序。
2. 退出 GitHub Desktop。
3. 重启并重新打开 GitHub Desktop。

> **注意**: 此问题并不总是稳定复现。

---

**预期结果**  
汉化应成功并保持有效。

**实际结果**  
汉化失败，且 `main.js` 文件被覆盖。

**推测**  
可能是由于 GitHub Desktop 更新了 `main.js` 文件，导致汉化失效。

**Comment by cngege** [comment]
- 从没遇到过这种情况
- （在汉化已经完成的情况下）也没有能成功复现这种情况
- 理论也不应该有这种情况

是GitHubDesktop重新还原了main.js文件的可能性比较小，检查一下是否是电脑上其他软件（比如安全软件）设置了文件保护之类的功能。  
另外 看你的描述有点歧义的感觉，询问下 `重现步骤`是否是在已经完成汉化（软件跑完打开GitHubdesktop汉化没问题）的情况下做的。

**Comment by afterow** [comment]
汉化是成功的，不过有退出以后重新打开汉化就失效了(有概率),看了文件的修改日期，发现是main.js被还原了，安全软件没有日志

**Comment by cngege** [comment]
看了下GitHubDesktop项目的近期提交内容，没有提到新增会检测js文件并还原的机制，后续如果出现这种情况也可检查一下系统日志，看看系统有没有对`C:\Users\【用户名】\AppData\Local\GitHub Desktop\【最新版本文件夹】\resources\app` 目录进行操作
